eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
server:
  port: 8081
spring:
  application:
    name: employee-service
  cloud:
    config:
      override-system-properties: false
      allow-override: true
      override-none: true
