server:
  port: 8080

spring:
  application:
    name: gateway-proxy

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    employee-service:
      path: /employees/**
      stripPrefix: false
    student-service:
      path: /students/**
      stripPrefix: false

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka